twig:
#  imports:
#    - { resource: twig_project_specific.yaml }

  default_path: '%kernel.project_dir%/templates'
  form_themes: [ 'bootstrap_4_layout.html.twig' ]
  globals:
    CheckIfUserService: '@App\Services\CheckIfUserService'
    CompanyDetailsService: '@App\Services\CompanyDetailsService'
    CountAllocatedWebsites: '@App\Services\CountAllocatedWebsites'
    CountBusinessContactsService: '@App\Services\CountBusinessContactsService'
    CountBusinessContactReferralsService: '@App\Services\CountBusinessContactReferralsService'
    CountPendingWebsiteInquiriesService: '@App\Services\CountPendingWebsiteInquiriesService'
    CountPhotoLocationsService: '@App\Services\CountPhotoLocationsService'
    CountPhotosService: '@App\Services\CountPhotosService'
    CountUserLogsService: '@App\Services\CountUserLogsService'
    ImportUserService: '@App\Services\ImportUserService'
    LanguagesService: '@App\Services\LanguagesService'
    PhotoAuthorsByLocation: '@App\Services\PhotoAuthorsByLocation'
    ProductService: '@App\Services\ProductService'
    TranslationsImportService: '@App\Services\TranslationsImportService'
    TranslationsWorkerService: '@App\Services\TranslationsWorkerService'
    WeatherService: '@App\Services\WeatherService'


when@test:
  twig:
    strict_variables: true

